#!/bin/bash
# ============================================================================
#  Installs every prerequisite for the desktop pod into a bare Ubuntu image.
#
#  FROM ubuntu:24.04
#  COPY install.sh /tmp/
#  RUN bash /tmp/install.sh && rm -rf /var/lib/apt/lists/*
#
#  This replaces the upstream project's host installer: no nginx, no TLS, no
#  fail2ban, no firewall, no systemd. Those belong to the pod and to the
#  Traefik reverse proxy in front of it.
#
#  Optional extras are opt-in via environment variables:
#    INSTALL_NODE=0       skip Node.js (only if the web client is a separate
#                         deployment; it defaults to on)
#    NODE_MAJOR=22        NodeSource major version to install
#    INSTALL_BROWSERS=1   Google Chrome (the dock's "Chrome" icon)
#    INSTALL_FIREFOX=1    Firefox
#    INSTALL_DOCS=1       LibreOffice
#    DISPLAY_GEOMETRY=1920x1080
#    VNC_PORT=5900        raw RFB port
#    VNC_WS_PORT=6900     websockify port
# ============================================================================
set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
export LC_ALL=C

VNC_GEOMETRY="${DISPLAY_GEOMETRY:-1920x1080}"
VNC_DEPTH="${VNC_DEPTH:-24}"
VNC_PORT="${VNC_PORT:-5900}"
VNC_WS_PORT="${VNC_WS_PORT:-6900}"
VNC_DISPLAY="${VNC_DISPLAY:-:1}"

log()  { echo -e "\033[0;32m[+]\033[0m $*"; }
warn() { echo -e "\033[1;33m[!]\033[0m $*"; }
die()  { echo -e "\033[0;31m[x]\033[0m $*" >&2; exit 1; }

# Assert a binary the image depends on actually exists, naming the package that
# provides it so a failure says where to look instead of just what is missing.
# Defined up here because the Node step below is the first thing to call it.
check_bin() {
    command -v "$1" >/dev/null 2>&1 \
        || die "'$1' is missing after install. It should come from '$2'."
}

[ "$(id -u)" -eq 0 ] || die "Must run as root (use docker build as root, or sudo)."
. /etc/os-release
case "$ID" in
    ubuntu) log "Detected $PRETTY_NAME" ;;
    *) warn "This script is written for Ubuntu; proceeding on $ID anyway." ;;
esac

# ─────────────────────────────────────────────────────────────────────────────
# 1. Pre-seed debconf so tzdata/locales do not prompt and hang the build.
#
#    Seed the debconf *database* only. Do NOT hand-write /etc/locale.gen or
#    /etc/default/keyboard: the postinst scripts of `locales` and
#    `keyboard-configuration` source those files, so anything written in the
#    wrong format makes dpkg fail with exit 127/1 and aborts the whole build.
# ─────────────────────────────────────────────────────────────────────────────
log "Seeding debconf defaults"
export DEBIAN_FRONTEND=noninteractive
debconf-set-selections <<'EOF'
tzdata tzdata/Areas select Etc
tzdata tzdata/Zones select UTC
locales locales/default_environment_locale select en_US.UTF-8
locales locales/locales_to_be_generated multiselect en_US.UTF-8
keyboard-configuration keyboard-configuration/layout select us
keyboard-configuration keyboard-configuration/modelcode select pc105
EOF

# ─────────────────────────────────────────────────────────────────────────────
# 2. Base system + build bits
# ─────────────────────────────────────────────────────────────────────────────
log "Installing base system"
apt-get update -qq
apt-get install -y -qq --no-install-recommends \
    ca-certificates curl wget gnupg apt-transport-https \
    locales tzdata keyboard-configuration xkb-data \
    procps psmisc tini

# The locales postinst should have generated this from the seed above; generate
# it by hand only if it somehow did not.
if ! locale -a 2>/dev/null | grep -qi '^en_US\.utf-\?8$'; then
    warn "en_US.UTF-8 was not generated by the locales postinst; generating it now"
    grep -q '^en_US.UTF-8 UTF-8' /etc/locale.gen 2>/dev/null \
        || echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen en_US.UTF-8 || true
fi
locale -a | grep -qi '^en_US\.utf-\?8$' || die "en_US.UTF-8 locale unavailable"

# ─────────────────────────────────────────────────────────────────────────────
# 3. Node.js runtime (needed by the web client)
#
#    Ubuntu 24.04 ships Node 18, which reached end of life in April 2025, so
#    take the current LTS from NodeSource instead. Set INSTALL_NODE=0 if this
#    image is a desktop-only pod and the web client lives elsewhere.
# ─────────────────────────────────────────────────────────────────────────────
if [ "${INSTALL_NODE:-1}" = "1" ]; then
    NODE_MAJOR="${NODE_MAJOR:-22}"
    log "Installing Node.js ${NODE_MAJOR}.x from NodeSource"

    # Keyring install rather than `curl | bash`, so apt verifies the repo key
    # and the image does not run a fetched script as root.
    install -d -m 0755 /etc/apt/keyrings
    curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
        | gpg --dearmor --yes -o /etc/apt/keyrings/nodesource.gpg
    chmod 0644 /etc/apt/keyrings/nodesource.gpg

    # `nodistro` keeps this working across Ubuntu point releases without
    # having to track the codename.
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" \
        > /etc/apt/sources.list.d/nodesource.list

    apt-get update -qq
    apt-get install -y -qq nodejs

    # The repo is no longer needed once the packages are installed.
    rm -f /etc/apt/sources.list.d/nodesource.list /etc/apt/keyrings/nodesource.gpg

    check_bin node nodejs
    check_bin npm  nodejs
    log "Node: $(node --version)  npm: $(npm --version)"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 4. X server plumbing
#
#    NOTE: this is the part the web client silently depends on. It shells out
#    to xclip, wmctrl, xrandr and cvt, so a container missing these renders the
#    desktop fine but silently loses clipboard sync, the window switcher and
#    resolution switching.
# ─────────────────────────────────────────────────────────────────────────────
log "Installing X server tools (xclip, wmctrl, xrandr, cvt, xauth)"
apt-get install -y -qq --no-install-recommends \
    x11-xserver-utils \
    x11-utils \
    xauth \
    xclip \
    xcvt \
    wmctrl \
    autocutsel \
    xserver-xorg-input-all \
    xserver-xorg-input-libinput \
    xkb-data \
    xdg-utils \
    dbus-x11 \
    policykit-1

# Verify every binary the web client and the session scripts actually invoke.
# Ubuntu splits these across more packages than you would expect -- `cvt` is in
# `xcvt`, not `x11-xserver-utils` -- and a missing one fails silently at
# runtime as a dock button that does nothing, so fail the build instead.
check_bin xrandr     x11-xserver-utils
check_bin cvt        xcvt
check_bin xclip      xclip
check_bin wmctrl     wmctrl
check_bin xauth      xauth
check_bin xdpyinfo   x11-utils
check_bin dbus-launch dbus-x11
log "X tooling verified (xrandr, cvt, xclip, wmctrl, xauth, xdpyinfo, dbus-launch)"

# ─────────────────────────────────────────────────────────────────────────────
# 5. TigerVNC + websockify
# ─────────────────────────────────────────────────────────────────────────────
log "Installing TigerVNC and websockify"
apt-get install -y -qq --no-install-recommends \
    tigervnc-standalone-server \
    tigervnc-common \
    websockify

check_bin Xtigervnc   tigervnc-standalone-server
check_bin vncconfig  tigervnc-common
check_bin websockify websockify
log "Xtigervnc: $(Xtigervnc -version 2>&1 | head -1)"

# ─────────────────────────────────────────────────────────────────────────────
# 6. XFCE desktop
# ─────────────────────────────────────────────────────────────────────────────
log "Installing XFCE (this is the bulk of the image)"
apt-get install -y -qq \
    xfce4 \
    xfce4-terminal \
    thunar \
    mousepad \
    xfce4-notifyd \
    xfce4-screenshooter \
    adwaita-icon-theme \
    dbus-user-session

log "Installing fonts (without these the desktop renders with tofu boxes)"
apt-get install -y -qq --no-install-recommends \
    xfonts-base \
    fonts-dejavu-core \
    fonts-liberation \
    fonts-noto-color-emoji \
    fontconfig
fc-cache -f >/dev/null 2>&1 || true

# These back the dock icons and the session itself. The web client resolves its
# dock against $PATH at startup, so a missing one silently shrinks the dock
# rather than erroring.
check_bin startxfce4     xfce4
check_bin xfce4-session  xfce4
check_bin xfce4-terminal xfce4-terminal
check_bin thunar         thunar
check_bin mousepad       mousepad
check_bin autocutsel     autocutsel
log "XFCE verified"

# ─────────────────────────────────────────────────────────────────────────────
# 7. Optional extras
# ─────────────────────────────────────────────────────────────────────────────
if [ "${INSTALL_BROWSERS:-0}" = "1" ]; then
    log "Installing Google Chrome"
    curl -fsSL -o /tmp/chrome.deb \
        https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    apt-get install -y -qq /tmp/chrome.deb || apt-get install -y -qq -f
    rm -f /tmp/chrome.deb
fi

if [ "${INSTALL_FIREFOX:-0}" = "1" ]; then
    # Ubuntu's `firefox` package is a snap transitional wrapper, which does not
    # work in a container. Use the Mozilla APT repo instead.
    log "Installing Firefox (Mozilla APT repo)"
    apt-get install -y -qq --no-install-recommends ca-certificates gnupg
    install -d -m 0755 /etc/apt/keyrings
    curl -fsSL https://packages.mozilla.org/apt/repo-signing-key.gpg \
        | gpg --dearmor -o /etc/apt/keyrings/packages.mozilla.org.asc
    echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] \
https://packages.mozilla.org/apt mozilla main" > /etc/apt/sources.list.d/mozilla.list
    apt-get update -qq
    apt-get install -y -qq firefox
fi

if [ "${INSTALL_DOCS:-0}" = "1" ]; then
    log "Installing LibreOffice"
    apt-get install -y -qq --no-install-recommends libreoffice-calc libreoffice-writer
fi

# ─────────────────────────────────────────────────────────────────────────────
# 8. Unprivileged runtime user
#
#    The desktop runs as this user, not root. Xtigervnc and XFCE both want a
#    writable $HOME for .Xauthority, ~/.vnc and D-Bus sockets, and running as
#    root would leave root-owned files that break the next start.
#
#    ubuntu:24.04 already ships an unprivileged `ubuntu` user at uid 1000,
#    which collides with the default DESKTOP_UID, so remove it first.
# ─────────────────────────────────────────────────────────────────────────────
DESKTOP_USER="${DESKTOP_USER:-desktop}"
DESKTOP_UID="${DESKTOP_UID:-1000}"
DESKTOP_GID="${DESKTOP_GID:-1000}"

existing_user="$(getent passwd "$DESKTOP_UID" | cut -d: -f1 || true)"
if [ -n "$existing_user" ] && [ "$existing_user" != "$DESKTOP_USER" ]; then
    log "uid $DESKTOP_UID is taken by '$existing_user'; removing it"
    userdel -r "$existing_user" >/dev/null 2>&1 || userdel "$existing_user" >/dev/null 2>&1 || true
fi

if ! id -u "$DESKTOP_USER" >/dev/null 2>&1; then
    log "Creating unprivileged user '$DESKTOP_USER' (uid $DESKTOP_UID)"
    groupadd -f -g "$DESKTOP_GID" "$DESKTOP_USER"
    useradd -m -u "$DESKTOP_UID" -g "$DESKTOP_GID" -s /bin/bash "$DESKTOP_USER"
fi

DESKTOP_HOME="$(getent passwd "$DESKTOP_USER" | cut -d: -f6)"

# ~/Desktop and ~/Downloads are where the web client's file transfer reads and
# writes, so they must exist and be owned by the runtime user.
mkdir -p "$DESKTOP_HOME/Desktop" "$DESKTOP_HOME/Downloads" "$DESKTOP_HOME/.vnc"
chown -R "${DESKTOP_UID}:${DESKTOP_GID}" "$DESKTOP_HOME"

# X11 unix sockets. X creates /tmp/.X11-unix itself but needs the directory to
# exist and be sticky; as non-root it cannot create it if the parent is not
# writable at build time.
mkdir -p /tmp/.X11-unix
chmod 1777 /tmp/.X11-unix

log "Runtime user: $DESKTOP_USER (uid $DESKTOP_UID), home $DESKTOP_HOME"

# ─────────────────────────────────────────────────────────────────────────────
# 9. X startup script
#
#    Xtigervnc runs this instead of a bare X server. Without it you get a grey
#    screen with no session.
# ─────────────────────────────────────────────────────────────────────────────
log "Writing XFCE VNC session startup script"
cat > /usr/local/bin/xfce-vnc-session <<'SESSION'
#!/bin/bash
# Started by Xtigervnc via -xstartup. Runs the desktop inside the X server,
# as the unprivileged desktop user.

# A per-uid D-Bus socket dir; $XDG_RUNTIME_DIR is often unset in containers,
# and /run/user/<uid> does not exist because logind is not running. /tmp is
# world-writable, so it is the only dependable place for this.
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/runtime-$(id -u)}"
mkdir -p "$XDG_RUNTIME_DIR"
chmod 700 "$XDG_RUNTIME_DIR"

# The web client reads $HOME/.Xauthority to reach this same X server, and the
# X server wrote it, so both sides are the same user and can read it.
export XAUTHORITY="${XAUTHORITY:-$HOME/.Xauthority}"

# Give the session its own D-Bus. XFCE panels and thunar need one.
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
    eval "$(dbus-launch --sh-syntax)"
    export DBUS_SESSION_BUS_ADDRESS
fi

export XDG_SESSION_TYPE=x11
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CURRENT_DESKTOP=XFCE

# Bridge the X clipboard to the VNC clipboard in both directions.
#   vncconfig  = VNC side  <-> X selections
#   autocutsel = PRIMARY   <-> CLIPBOARD
vncconfig -nowin >/dev/null 2>&1 &
autocutsel -fork -selection CLIPBOARD >/dev/null 2>&1 &

# Network manager applet is meaningless in a pod and spams errors on a
# machine-id it can never reach.
xfce4-session >/dev/null 2>&1 &
SESSION
chmod +x /usr/local/bin/xfce-vnc-session

# ─────────────────────────────────────────────────────────────────────────────
# 10. Xtigervnc launcher
#
#    -SecurityTypes None is deliberate: the browser client has no VNC password
#    field and sends an empty credential. If you enable VNC auth you must also
#    change client/js/desktop.js to prompt for one.
# ─────────────────────────────────────────────────────────────────────────────
log "Writing Xtigervnc launcher"
cat > /usr/local/bin/start-vnc <<'STARTVNC'
#!/bin/bash
# Start Xtigervnc with the XFCE session on DISPLAY, as an unprivileged user.
set -euo pipefail

DISPLAY_NUM="${VNC_DISPLAY:-:1}"
GEOMETRY="${DISPLAY_GEOMETRY:-1920x1080}"
DEPTH="${VNC_DEPTH:-24}"
RFB_PORT="${VNC_PORT:-5900}"
WS_PORT="${VNC_WS_PORT:-6900}"

# Nothing here needs root, and running as root leaves root-owned files in the
# user's home that break the next start. Fail loudly rather than half-working.
if [ "$(id -u)" -eq 0 ]; then
    echo "Refusing to start the desktop as root." >&2
    echo "Run the container with USER ${DESKTOP_USER:-desktop} instead." >&2
    exit 1
fi

# $HOME must be writable: Xtigervnc writes .Xauthority there and the web client
# reads it back. A root-owned home is the usual cause of a black screen.
: "${HOME:?HOME must be set for the desktop user}"
if [ ! -w "$HOME" ]; then
    echo "HOME ($HOME) is not writable by $(id -un)." >&2
    exit 1
fi

# X11 socket dir. Created at build time with the sticky bit; create it here too
# in case /tmp was mounted fresh.
mkdir -p /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix 2>/dev/null || true

# Clear stale locks from an unclean shutdown. These may be owned by another
# uid from a previous container layer, so failure here is not fatal.
rm -f "/tmp/.X${DISPLAY_NUM#:}-lock" "/tmp/.X11-unix/X${DISPLAY_NUM#:}" 2>/dev/null || true

export DISPLAY="$DISPLAY_NUM"
export HOME
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/tmp/runtime-$(id -u)}"
mkdir -p "$XDG_RUNTIME_DIR" && chmod 700 "$XDG_RUNTIME_DIR"

Xtigervnc "$DISPLAY_NUM" \
    -geometry "$GEOMETRY" \
    -depth "$DEPTH" \
    -rfbport "$RFB_PORT" \
    -localhost yes \
    -SecurityTypes None \
    -AlwaysShared \
    -AcceptKeyEvents \
    -AcceptPointerEvents \
    -SendCutText \
    -AcceptCutText \
    -xstartup /usr/local/bin/xfce-vnc-session \
    -NeverStartErrorDialog &

VNC_PID=$!

# Wait for the X server to accept connections before declaring success
for _ in $(seq 1 30); do
    if xdpyinfo -display "$DISPLAY_NUM" >/dev/null 2>&1; then
        echo "X server ready on $DISPLAY_NUM (${GEOMETRY}, RFB :${RFB_PORT})"
        break
    fi
    if ! kill -0 "$VNC_PID" 2>/dev/null; then
        echo "Xtigervnc died during startup" >&2
        exit 1
    fi
    sleep 0.5
done

# websockify exposes the same RFB stream over WebSocket.
#
# The Debian websockify package does NOT pull in noVNC, and we do not want it
# to: the web client in this repo serves its own bundled noVNC. So --web is
# only passed if a noVNC tree happens to be present (e.g. you installed the
# `novnc` package yourself).
NOVNC_WEB_ARGS=()
if [ -d /usr/share/novnc ]; then
    NOVNC_WEB_ARGS=(--web=/usr/share/novnc)
fi

echo "websockify :${WS_PORT} -> 127.0.0.1:${RFB_PORT}"
websockify ${NOVNC_WEB_ARGS[@]+"${NOVNC_WEB_ARGS[@]}"} "0.0.0.0:${WS_PORT}" "127.0.0.1:${RFB_PORT}" &
WS_PID=$!

# Exit if either dies so the container restarts rather than serving nothing
wait -n "$VNC_PID" "$WS_PID"
echo "A VNC process exited; shutting down."
kill "$VNC_PID" "$WS_PID" 2>/dev/null || true
STARTVNC
chmod +x /usr/local/bin/start-vnc

# ─────────────────────────────────────────────────────────────────────────────
# 11. Wrap Xtigervnc's own launcher so `startvnc` behaves predictably
# ─────────────────────────────────────────────────────────────────────────────
ln -sf /usr/local/bin/start-vnc /usr/local/bin/start-desktop

# ─────────────────────────────────────────────────────────────────────────────
# 12. Cleanup
# ─────────────────────────────────────────────────────────────────────────────
log "Cleaning apt cache"
apt-get clean
rm -rf /var/lib/apt/lists/*

# ─────────────────────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────────────────────
cat <<SUMMARY

  Prerequisites installed.

  Scripts written:
    /usr/local/bin/start-vnc        Xtigervnc + XFCE + websockify
    /usr/local/bin/xfce-vnc-session XFCE session run inside X

  Defaults:
    display   ${VNC_DISPLAY}  ${VNC_GEOMETRY} depth ${VNC_DEPTH}
    RFB       :${VNC_PORT}  (loopback only)
    websocket :${VNC_WS_PORT}  (bound to 0.0.0.0)

  Installed runtimes:
$(if [ "${INSTALL_NODE:-1}" = "1" ]; then echo "    node       $(node --version), npm $(npm --version)"; fi)

  CMD ["start-vnc"]

  Next: add the web client as a second container in the same pod, or run it
  as its own deployment pointed at the websockify port above.

SUMMARY